// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyAsp.Data;

#nullable disable

namespace MyAsp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyAsp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Artificial Intelligence",
                            Name = "AI"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Machine Learning",
                            Name = "ML"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Analysis of large data sets",
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Building and maintaining websites",
                            Name = "Web Development"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Developing mobile applications",
                            Name = "Mobile Development"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Development and operations practices",
                            Name = "DevOps"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Protecting systems and data",
                            Name = "Cybersecurity"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Using cloud-based infrastructure",
                            Name = "Cloud Computing"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Internet of Things devices and systems",
                            Name = "IoT"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Decentralized ledger technology",
                            Name = "Blockchain"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Creating video games",
                            Name = "Game Development"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Designing user interfaces and experiences",
                            Name = "UI/UX Design"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Programming hardware devices",
                            Name = "Embedded Systems"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Augmented and Virtual Reality technologies",
                            Name = "AR/VR"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Handling massive amounts of data",
                            Name = "Big Data"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Design and operation of robots",
                            Name = "Robotics"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Ensuring software quality",
                            Name = "Software Testing"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Connecting computers and devices",
                            Name = "Networking"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Promoting products online",
                            Name = "Digital Marketing"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Online buying and selling",
                            Name = "E-Commerce"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
